import { z } from "zod";

export const DealLifecycleStatusSchema = z.enum([
  "DISCLOSURE_REQUIRED",
  "DISCLOSURE_PENDING",
  "DISCLOSURE_SIGNED",
  "MOCKUP_SUBMITTED",
  "LENDER_REVIEW",
  "LENDER_COUNTER",
  "BUYER_REAUTH_PENDING",
  "LENDER_FINAL_APPROVAL",
  "FINAL_PACKAGE_GENERATED",
  "AWAITING_LIVE_SIGNATURES",
  "AWAITING_FUNDING_UPLOAD",
  "FUNDED",
  "AUTHORIZED_FOR_STRUCTURING",
  "GREEN_STAGE",
  "RISC_UNSIGNED_REVIEW",
  "RISC_LENDER_FINAL",
  "FIRST_GREEN_PASSED",
  "AUTHORITATIVE_LOCK",
  "GENERATING_CLOSING_PACKAGE",
  "CLOSING_PACKAGE_READY",
  "CONSUMMATED",
]);

export const GreenStageDocTypeSchema = z.enum(["DEALER_UPLOAD", "INSURANCE", "CREDIT_REPORT_UPLOAD"]);

export type DealLifecycleStatus = z.infer<typeof DealLifecycleStatusSchema>;
